### ISSUE TITLE
feature: Autocomplete through something like ctags for Dart.

### ISSUE THREAD

**Issue by austincummings** [guillermooo/dart-sublime-bundle#119]
Is this something we would want to do? Something like ctags for Dart where it could be run every minute or so to pluck out relevant "tags" in open Dart source files. We could then add them to the Sublime autocomplete (if that is possible). It would also allow us to jump to tags right? I don't have much knowledge of the Sublime API but I am willing to write the tags script.

**Comment by guillermooo** [comment]
Closing, as autocompletion will be provided via the analsysis server.
