### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by DmitryBochkarev** [guillermooo/dart-sublime-bundle#36]
Are there any plans to add auto-completion?

**Comment by paulevans** [comment]
Just adding my +1 here. Is there a reference implementation for another editor out there and documented to look at? I miss the way the Dart Editor auto completes Futures etc.

**Comment by guillermooo** [comment]
AC is next on my list. It should be the next major feature in the plugin.

**Comment by paulevans** [comment]
@guillermooo you are going to be a lot of people's favourite person when that goes in :)

**Comment by guillermooo** [comment]
The suggestions from the DAS are already flowing through the plugin internals in the dev build. I just need to wire them up to the UI, and by "just" I mean that's the hardest part!

**Comment by guillermooo** [comment]
#528
