### ISSUE TITLE
Default blue underline for warning hard to read with default theme

### ISSUE THREAD

**Issue by sethladd** [guillermooo/dart-sublime-bundle#364]
![screen shot 2014-09-29 at 2 59 39 pm](https://cloud.githubusercontent.com/assets/5479/4450313/ff9fb4e6-4823-11e4-9ba3-b99c705d0f69.png)

Could we consider a different underline color than blue? Maybe yellow?

**Comment by guillermooo** [comment]
The plugin's now using default scopes with their default colors. I've requested general-purpose info, warning and error colors so that plugins don't have to mess with the color schemes, which usually doesn't produce great results.

**Comment by guillermooo** [comment]
Hm. Well, the above applies to the analysis server, not to the linter. I'll have to look into that.

**Comment by guillermooo** [comment]
Closing as the linter is now deprecated in favor of the analysis server.
