### ISSUE TITLE
Feature: Display error or warning when hover over issue in code

### ISSUE THREAD

**Issue by sethladd** [guillermooo/dart-sublime-bundle#365]
It would be fantastic if there's a way to get more information about a particular error or warning.

Take, for example, this:

```
import 'dart:async';

main() {
  var i = 0;
  new Timer.periodic(const Duration(seconds: 1), (_) {
    print('hello ${i++}');
    i.bar();
    i.foo();
  });
}

Future doStuff() => new Future.value(true);
```

The analyzer correctly determines that `i.bar()` and `i.foo()` are incorrect and Sublime highlights with a blue underline. Yay!

However, I don't know how to tell what the actual error is. There is the output in the Sublime console, but it's not easy to determine which line in the output goes to which error in the code.

**Comment by guillermooo** [comment]
Errors are now displayed to the user. Hovering over errors will have to wait until the tooltip is made available in the stable build of ST. Closing for now.

**Comment by sethladd** [comment]
Thanks! How are the errors displayed?

**Comment by guillermooo** [comment]
https://plus.google.com/u/0/113185854601778221871/posts/7vGZ5jq3Zp5
