### ISSUE TITLE
Commenting out code is using three slashes instead of two.

### ISSUE THREAD

**Issue by richardeakin** [guillermooo/dart-sublime-bundle#431]
First, thanks for the nice package, I use it every day.

Since a recent release, when I try to comment out code I'm working on, it is using three slashes, whereas with every other language I work in it uses two. I believe this is because of #415, though I think that Dart's style guide is only meaning that you create documentation comments with three slashes.

Is it possible to set this back to two? If there is a config setting, I'd be happy to change it on my end (though I really do think that ideally commenting out code would just ust two slashes, as this is the norm).

**Comment by guillermooo** [comment]
Implemented.
