### ISSUE TITLE
SDK assumed to be in PATH for "Run Dart Analyzer" command

### ISSUE THREAD

**Issue by theawesomestllama** [guillermooo/dart-sublime-bundle#441]
Running the "Run Dart Analyzer" command produces "[Errno 2] No such file or directory: 'dartanalyzer'" when the Dart SDK is not in the PATH. It seems the problem is that the commands in docgen.py should be using path_to_analyzer (and path_to_docgen) from the SDK class and they are not.

**Comment by guillermooo** [comment]
Dart analyzer has been obsoleted. Closing.
