### ISSUE TITLE
Incorrect syntax highlight 

### ISSUE THREAD

**Issue by jackhftang** [guillermooo/dart-sublime-bundle#444]
The `else if` part is not highlighted, I am using sublime text 3 on OSX
![image](https://cloud.githubusercontent.com/assets/1190545/6090514/038557a6-aeb7-11e4-937b-dd70554df994.png)

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by guillermooo** [comment]
cc @sethladd 

Thanks for the report.

`dartformat` changes `else if(true` to `else if (true`. The second version is highlighted just fine.

If I try to correct the hilighting shown above, the rule for funcs returning user-defined types will have to be disabled. Given that `dartformat` recommends a different style in this case, should we really change this?

**Comment by sethladd** [comment]
This would be nice to fix, but it's probably a low priority. Certainly, patches welcome.

**Comment by jackhftang** [comment]
Keeping if... else... in one line is okay, but not two. I know this is not a [recommended style](https://www.dartlang.org/articles/style-guide/#do-use-curly-braces-for-all-flow-control-structures). However, it is in correct grammar and looks strange comparing to other C-like languages.

![image](https://cloud.githubusercontent.com/assets/1190545/6287840/a119ac7c-b94f-11e4-9e73-b8e9c0ed405d.png)
