### ISSUE TITLE
Analyzer enum support

### ISSUE THREAD

**Issue by Hadoukanen** [guillermooo/dart-sublime-bundle#453]
dartanalyzer needs "--enable-enum" in order to work correctly, for the time being at least.
This did not fix it as i thought.

analyzer.py
row 348:
        AnalysisServer.server = PipeServer([sdk.path_to_dart,
                            sdk.path_to_analysis_snapshot,
                           '--sdk={0}'.format(sdk.path),
                           '--enable-enum'])

// Happy coding

**Comment by guillermooo** [comment]
@sethladd  @bwilkerson

Is there a way to tell the server to recognize enums?

**Comment by sethladd** [comment]
I was under the impression that the AS already understands enums, without requiring a flag.

cc @jwren to confirm

**Comment by jwren** [comment]
Correct, I just verified this in the bleeding_edge.

The dart analyzer is not the analysis server, the server has no enable enum flag, and never has.  The analysis server uses the dartanalyzer (command line version of the analyzer), it has a *deprecated* --enable-enum flag, it is enabled by default.  Using the latest server/ dartanalyzer/ analysis engine directly will have enum support with no flag passed.

**Comment by jwren** [comment]
Also... same goes for the async support.

**Comment by guillermooo** [comment]
Thanks @jwren! I'll close this one then. @Hadoukanen, feel free to re-open if the problem persists.

**Comment by Hadoukanen** [comment]
I was using dart-sdk 1.8.5. The 1.9.0 is working correctly. I thought it would work on a stable release of dart sdk.

**Comment by guillermooo** [comment]
@Hadoukanen The latest Dart SDK ships with analysis server v 0.0.1 (you should see this in ST's console at startup). This is why enums trip it up. I got mightily confused because of this too. I suppose later versions of server deal with them just fine (haven't tried myself, though).
