### ISSUE TITLE
How to see what the error or warning is?

### ISSUE THREAD

**Issue by sethladd** [guillermooo/dart-sublime-bundle#469]
I just tried the analyzer server integration. Really cool! I saw feedback without needing to save my file.

However, how do I see the actual error or warning? I see the `!` and the underlines, but I'd like to see the message.

![screen shot 2015-02-27 at 3 33 44 pm](https://cloud.githubusercontent.com/assets/5479/6423120/4a2e19f6-be96-11e4-9f79-cd49baca3786.png)

**Comment by sethladd** [comment]
I tried hovering and right clicking. I also looked inside the console.

**Comment by Fox32** [comment]
I don't think that #365 is fixed yet.

**Comment by guillermooo** [comment]
Thanks for the report. This feature is high up on my todo list for the plugin. ST recently grew the ability of displaying an html-based tooltip, so it could be a good fit for this case.

**Comment by sethladd** [comment]
Oh, great to hear ST3 has the framework to show the feedback!

**Comment by guillermooo** [comment]
Fixed by #481
