### ISSUE TITLE
Ignore dart_linter_active if dart_enable_analysis_server is turned on?

### ISSUE THREAD

**Issue by sethladd** [guillermooo/dart-sublime-bundle#470]
The new plugin version ships with `"dart_enable_analysis_server": true,` but I still had `"dart_linter_active": true,` in my User settings.

When I saved my file, it looks like the batch analyzer still ran.

If  `"dart_enable_analysis_server": true,` then should we ignore `"dart_linter_active": true,` ?

**Comment by guillermooo** [comment]
Good catch. I'll make the fix and deprecate the linter's event-based operation.
