### ISSUE TITLE
Analysis server not displaying errors/warnings for a single file not in a pub layout

### ISSUE THREAD

**Issue by sethladd** [guillermooo/dart-sublime-bundle#483]
Files in a pure pub layout are being analyzed correctly. Pretty cool!

However, if you have a single file in an otherwise empty directory, the analysis server does not display errors or warnings.

Looks like the plugin attempts to find a pubspec file, and if it fails, it just returns instead of sending a AnalysisSetAnalysisRootsRequest.

https://github.com/guillermooo/dart-sublime-bundle/blob/21096f24d8a34668d54ad31b8902ab5c709c1c07/analyzer.py#L344

Thanks for taking a look!

**Comment by sethladd** [comment]
This worked for us:

Replace lines at 345
            _logger.debug('did not found pubspec.yaml in path: %s', path)
            return

with

            p = os.path.dirname(path)
            _logger.debug('did not find pubspec.yaml in path: %s', path)
            _logger.debug('set root to: %s', p)

**Comment by sethladd** [comment]
We have internal customers using the plugin that would be very happy with this patch. :)

**Comment by guillermooo** [comment]
I'll take a look at this. Thanks for reporting!

**Comment by guillermooo** [comment]
Fixed. The commit above does not enable full support for loose dart files, though. For example, you cannot run a .dart file that doesn't belong to a standard pub package.
