### ISSUE TITLE
A way to silence TODO feedback when using analysis service

### ISSUE THREAD

**Issue by sethladd** [guillermooo/dart-sublime-bundle#487]
Analysis service integration is awesome.

We have code that has a bunch of `@TODO`. That feedback shows up in the console as output from the analysis service.

Can we configure analysis service to not report `@TODO` , as an option in the User's preferences for the plugin?

Thanks!

**Comment by guillermooo** [comment]
Hm. Can't repro this. How's `@TODO` supposed to be used?

**Comment by jwren** [comment]
The idea is location in source that are formatted like this:

// TODO do something

show up as a lower priority warning (TODO type) with the Errors/Warnings/Hints.  See

http://htmlpreview.github.io/?https://github.com/dart-lang/bleeding_edge/blob/master/dart/pkg/analysis_server/doc/api.html#type_AnalysisErrorType

**Comment by guillermooo** [comment]
TODO infos removed from errors report.
