### ISSUE TITLE
display analyzer errors as a tooltip at the error location

### ISSUE THREAD

**Issue by guillermooo** [guillermooo/dart-sublime-bundle#494]
![dart-errors-tooltip](https://cloud.githubusercontent.com/assets/684948/7549671/9bc46d2a-f63f-11e4-9102-7fe7edd03f9b.png)

**Comment by guillermooo** [comment]
![dart-errors-tooltip2](https://cloud.githubusercontent.com/assets/684948/7549715/117203b4-f642-11e4-8ddc-e15635e9f48f.png)

**Comment by sethladd** [comment]
Nice!!

**Comment by guillermooo** [comment]
#510
