### ISSUE TITLE
 missing "dart_sdk_path" setting

### ISSUE THREAD

**Issue by ricker07** [guillermooo/dart-sublime-bundle#497]
================================================================================
MESSAGE:
missing "dart_sdk_path" setting

CONFIGURATION:
--------------------------------------------------------------------------------
editor version: 3083 (stable)
--------------------------------------------------------------------------------
os: linux (x64)
--------------------------------------------------------------------------------
dart_sdk_path: None
================================================================================

**Comment by SangSatori** [comment]
Fixed it on my end by editing the package's JSON settings. Edit the file so it looks something [like this gist](https://gist.github.com/SangSatori/bc29371b1ff730373f22). I'm using Arch Linux with Dart SDK 1.10.0.

**Comment by guillermooo** [comment]
https://github.com/guillermooo/dart-sublime-bundle/wiki/Installation%20and%20Basic%20Configuration#set-dart_sdk_path
