### ISSUE TITLE
Error loading syntax file on 1.4.0 Sublime Build 3083 (stable channel)

### ISSUE THREAD

**Issue by ceronman** [guillermooo/dart-sublime-bundle#516]
I get the following error the first time a file is analyzed:

```
error: Error loading syntax file "Packages/Dart/Support/Analyzer Output.sublime-syntax": Error parsing plist xml: expected < in file Packages/Dart/Support/Analyzer Output.sublime-syntax on line: 1
```

Here is a screenshot of the error: http://pasteboard.co/qymb7ZT.png

I confirm this happens both on Linux and Mac OS X with the latest **stable** build of Sublilme Text. I guess the new syntax format is not yet supported in the latest stable build.

**Comment by guillermooo** [comment]
Hm. More than likely. I haven't used beta versions for years (I'm on the dev channel). Supporting both channels will be a pain. I don't think Package Control foresees this scenario, but I may be mistaken.

Anyway, thanks! I'll think about it.

Hopefully, though, the new syntax stuff will be enabled soon in a beta version. It seems the new regex engine is mostly ready.

**Comment by sethladd** [comment]
Thanks @guillermooo this is now fixed. Should we close?
