### ISSUE TITLE
Criptic error

### ISSUE THREAD

**Issue by pstjvn** [guillermooo/dart-sublime-bundle#518]
When I start st3 and open a directory that contains dart project I get this:

Error loading syntax file "Packages/Dart/Support/Analyzer Output.sublime-syntax": Error parsing plist xml: expected < in file Packages/Dart/Support/Analyzer Output.sublime-syntax on line: 1

What does it mean and how should i fix it?

**Comment by sethladd** [comment]
Just ran into this myself.

![screen shot 2015-05-28 at 6 06 57 pm](https://cloud.githubusercontent.com/assets/5479/7874428/60acdb8a-0564-11e5-80bd-b22e9e364ed3.png)


Dart 1.10.0
Sublime 3083
Dart plugin 1.4.0

**Comment by guillermooo** [comment]
That happens because .sublime-syntax if a new format only available in ST dev channel. :/

I guess we need a branch for 'future/dev' in addition to 'master'. The problem is, I don't think Package Control supports multiple branches, so we'll be stuck with the latests ST beta for releases.

**Comment by sethladd** [comment]
Thanks for checking it out. Looking forward to using Sublime with Dart again :)

**Comment by sethladd** [comment]
Confirmed, I'm back up and running!
