### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by sethladd** [guillermooo/dart-sublime-bundle#520]
Fresh install of Sublime, Package Control, and the Dart plugin.

![screen shot 2015-05-28 at 6 08 46 pm](https://cloud.githubusercontent.com/assets/5479/7874446/a39a17aa-0564-11e5-99c9-f86e48e0c399.png)

The only thing in my user settings for the Dart plugin is the path to the core SDK.

**Comment by sethladd** [comment]
Related to https://github.com/guillermooo/dart-sublime-bundle/issues/518 ?

**Comment by guillermooo** [comment]
Yes, it most likely is. I only use the dev channel myself, so I forget about the beta. I guess I'll have to downgrade my ST.

**Comment by sethladd** [comment]
Thanks! Fixed now.
