### ISSUE TITLE
assert word is not highlighting

### ISSUE THREAD

**Issue by sethladd** [guillermooo/dart-sublime-bundle#524]
assert is a reserved word. Should we highlight it?

![screen shot 2015-05-29 at 8 41 12 am](https://cloud.githubusercontent.com/assets/5479/7886473/266b1fba-05df-11e5-8f54-f526d4eec692.png)

**Comment by sethladd** [comment]
cc @eseidel

**Comment by eseidelGoogle** [comment]
https://www.dartlang.org/docs/dart-up-and-running/ch02.html#keywords

I'm not sure which name to use.  Probably "keyword.control.assert.dart".

**Comment by eseidelGoogle** [comment]
![screenshot from 2015-05-29 13 12 37](https://cloud.githubusercontent.com/assets/11857803/7891793/70a80d7a-0604-11e5-9185-fc398f00b0ea.png)
