### ISSUE TITLE
No support for stand-alone .dart files (not in a package dir)

### ISSUE THREAD

**Issue by sethladd** [guillermooo/dart-sublime-bundle#525]
Now running plugin 1.4.1 with Dart 1.10.0.

I have a single test.dart file:

```
main(List<String> args) async {
	assert(true);
	print('hi');
	await foo();
	try {
		// stuff
	} catch {
		notHere();
	}
}

foo() {}
```

which lives on my desktop.

Expected: a warning that notHere() doesn't exist.

Actual: no warning.

Screenshot:

![screen shot 2015-05-29 at 8 57 16 am](https://cloud.githubusercontent.com/assets/5479/7886732/e03c3cca-05e0-11e5-9db1-4936724c9de1.png)

(see "unknown include #regex.dart" in console... related?)

**Comment by sethladd** [comment]
Here's what webstorm shows:

![screen shot 2015-05-29 at 9 02 17 am](https://cloud.githubusercontent.com/assets/5479/7886825/762b5734-05e1-11e5-8135-655a205fdab3.png)

**Comment by guillermooo** [comment]
It may be that files under "test" are ignored altogether by the DAS.

**Comment by guillermooo** [comment]
I mean, in the Dart plugin.

**Comment by sethladd** [comment]
hm, the file 'test.dart' isn't under test. It's in the Desktop directory.

**Comment by guillermooo** [comment]
Yes, it must be the plugin's fault, but I was thinking maybe the plugin makes the DAS ignore files under "test" in a pub package. Not sure at all, though. Need to look into it.

Is your file in a pub package folder structure?

**Comment by sethladd** [comment]
My test.dart file is literally inside of the Desktop directory. It's the only file in the Desktop directory.

![screen shot 2015-05-29 at 9 13 18 am](https://cloud.githubusercontent.com/assets/5479/7887044/fa0c9792-05e2-11e5-9eb5-a7cd2398e53d.png)

**Comment by guillermooo** [comment]
Thanks. If you get no errors shown at all for broken code, then probably a single-file scenario like this one is unsupported atm by the plugin. I think it always checks for a pubspec.yaml and ignores files if it doesn't find one.

**Comment by sethladd** [comment]
Thanks for checking it out. The sublime plugin should work for a single stand-alone file, if that file is a library (not a part).

**Comment by sethladd** [comment]
Hi,

We just ran into this scenario with an internal user. We wanted to open Sublime, create a new Dart file, and analyze it. We didn't have a pubspec.yaml file.

What do you need from us to make this scenario work? :)

Thanks!!

**Comment by guillermooo** [comment]
I seem to remember in the very beginning we decided against it. But can't really say for sure any more.

The plugin should be modified to allow this. I don't think it will be too much work, but I havent' gotten around to it yet.

**Comment by sethladd** [comment]
Perhaps the issue is... how do we know if we're in a Dart project?

If I have an empty directory, with a single Dart file (which is an entry point or a library file (not a part file)), I would want to treat that as a "Dart project".

But, this would require us to assume a bunch more about the environment. So I'll start a thread on analyzer-discuss@ to see what other people think.

**Comment by sethladd** [comment]
Some logic and ideas for how to detect a Dart project. https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/HVLgtVXyB18

**Comment by sethladd** [comment]
In the meantime, I updated https://github.com/guillermooo/dart-sublime-bundle/wiki/Installation-and-Basic-Configuration with explicit instructions to add a pubspec.yaml file. Hope that helps!

**Comment by guillermooo** [comment]
Just tried with a sindle main.dart file inside an otherwise empty folder and everything seems to be working (using repo's head, not latest release). I don't remember changing anything related to this scenario.

![dart-standalone](https://cloud.githubusercontent.com/assets/684948/8139466/45d4f080-1154-11e5-98cc-da3b25c54e5a.png)

**Comment by sethladd** [comment]
Thanks!
